# Generated by Django 3.0.5 on 2020-04-28 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(max_length=100, verbose_name='Type de question')),
                ('question_text', models.CharField(max_length=500)),
                ('difficulty', models.CharField(max_length=10, verbose_name='Difficulté')),
                ('note', models.SmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='questions')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_actuel', models.IntegerField()),
                ('niveau_actuel', models.CharField(max_length=50, verbose_name='Niveau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=100, verbose_name='Réponses')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Réponse correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiztest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_test', models.CharField(max_length=50, verbose_name='difficulté du test')),
                ('questions', models.ManyToManyField(to='quiz.Question')),
                ('users', models.ManyToManyField(to='quiz.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(verbose_name='Date de test')),
                ('score_test', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_devoir', models.CharField(max_length=100, verbose_name='Type de devoir')),
                ('difficulty_devoir', models.CharField(max_length=50, verbose_name='niveau du devoir')),
                ('duree', models.IntegerField(verbose_name='durée estimée')),
                ('contenu', models.FileField(null=True, upload_to='devoirs/%Y/%m/%d/')),
                ('users', models.ManyToManyField(to='quiz.Utilisateur')),
            ],
        ),
    ]
