# Generated by Django 3.0.5 on 2020-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='duree',
            field=models.IntegerField(verbose_name='durée estimée (min)'),
        ),
    ]
