# Generated by Django 3.0.5 on 2020-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoirs',
            name='contenu',
            field=models.FileField(null=True, upload_to='devoirs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='questions'),
        ),
    ]
