# Generated by Django 3.0.5 on 2020-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200430_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='total_question',
            field=models.IntegerField(default=0, verbose_name='nombre total de réponse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='total_questions_correctes',
            field=models.IntegerField(default=0, verbose_name='nombre de total de réponses correcte'),
        ),
    ]
