# Generated by Django 3.0.5 on 2020-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200430_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponses',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Réponse correct'),
        ),
    ]
