# Generated by Django 3.0.5 on 2020-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200503_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponses',
            name='answers',
        ),
        migrations.AddField(
            model_name='reponses',
            name='wrong_answers',
            field=models.CharField(max_length=100, null=True, verbose_name='Réponses Incorrectes'),
        ),
        migrations.AlterField(
            model_name='reponses',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True, verbose_name='Réponses correctes'),
        ),
    ]
