# Generated by Django 3.0.5 on 2020-05-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200503_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='total_question',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='total_questions_correctes',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='total_reponse',
            field=models.IntegerField(default=0, verbose_name='nombre total de reponse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='total_reponse_correctes',
            field=models.IntegerField(default=0, verbose_name='nombre de total de reponse correcte'),
        ),
    ]
