# Generated by Django 3.0.5 on 2020-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200503_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='texte',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='reponses',
            name='correct_answer',
            field=models.CharField(max_length=400, null=True, verbose_name='Réponses correctes'),
        ),
        migrations.AlterField(
            model_name='reponses',
            name='wrong_answers',
            field=models.CharField(max_length=400, null=True, verbose_name='Réponses Incorrectes'),
        ),
    ]
