# Generated by Django 3.0.5 on 2020-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200510_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau_actuel',
            field=models.CharField(default='Niveau 1', max_length=50, verbose_name='Niveau'),
        ),
    ]
