# Generated by Django 3.0.5 on 2020-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200510_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztest',
            name='difficulty_test',
            field=models.CharField(max_length=50, verbose_name='Niveau du test'),
        ),
    ]
