# Generated by Django 3.0.5 on 2020-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200511_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztest',
            name='users',
            field=models.ManyToManyField(blank=True, to='quiz.Utilisateur'),
        ),
    ]
